#include "shell.h"
#include "pmm.h"
#include "heap.h"
#include "../drivers/screen.h"
#include "../drivers/keyboard.h"
#include "../drivers/timer.h"
#include "../drivers/rtc.h"
#include "vfs.h"
#include "task.h"
#include "syscall.h"
#include "elf.h"
#include "pci.h"
#include "net.h"
#include "ata.h"
#include "usb.h"
#include "../drivers/speaker.h"
#include "gui.h"
#include "security.h"
#include "sha256.h"
#include "pkg.h"
#include "smp.h"
#include "power.h"
#include "klog.h"
#include "html.h"
#include "../drivers/rtl8139.h"
#include "net_io.h"
#include "arp.h"
#include "udp.h"
#include "tcp.h"
#include "net_pump.h"
#include "dhcp_real.h"
#include "dns_real.h"
#include "../include/types.h"

static const char* HOME_PAGE =
    "<h1>Welcome to Vyro OS</h1>"
    "<p>This page is rendered by <b>VyroBrowser</b>, a minimal HTML "
    "engine running inside the kernel on the framebuffer.</p>"
    "<h2>Features built from scratch</h2>"
    "<ul>"
    "<li>64-bit kernel, ring 3 user mode, ELF loader</li>"
    "<li>Networking stack, ATA disk, USB detection</li>"
    "<li>Window manager, sound, SHA-256 security</li>"
    "<li>Package manager, SMP detection, ACPI power</li>"
    "</ul>"
    "<p>Visit <a>github.com/Gaurav06120714/VyroOs</a> for source.</p>"
    "<p><b>$0 budget. 100% from scratch.</b></p>";

// Embedded user ELF binary (generated by Makefile into build/user_init.c)
extern const unsigned char user_init_elf[];
extern const unsigned int  user_init_elf_len;

// ─────────────────────────────────────────────────
// Userland-style syscall wrappers — invoke int 0x80
// (exactly how a user program would call the kernel)
// ─────────────────────────────────────────────────
static uint64_t do_syscall(uint64_t num, uint64_t arg1) {
    uint64_t ret;
    __asm__ volatile("int $0x80"
                     : "=a"(ret)
                     : "a"(num), "D"(arg1)
                     : "memory");
    return ret;
}

// ─────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────
#define MAX_INPUT      256
#define MAX_ARGS       16
#define HISTORY_SIZE   10

// Arrow key special values (set by keyboard driver)
#define KEY_UP    0x01
#define KEY_DOWN  0x02
#define KEY_LEFT  0x03
#define KEY_RIGHT 0x04

// ─────────────────────────────────────────────────
// String utilities (no stdlib in freestanding env)
// ─────────────────────────────────────────────────
static int kstrlen(const char* s) {
    int i = 0;
    while (s[i]) i++;
    return i;
}

static int kstrcmp(const char* a, const char* b) {
    while (*a && *b && *a == *b) { a++; b++; }
    return *a - *b;
}

static void kstrcpy(char* dst, const char* src) {
    while ((*dst++ = *src++));
}

// ─────────────────────────────────────────────────
// Command history ring buffer
// ─────────────────────────────────────────────────
static char    history[HISTORY_SIZE][MAX_INPUT];
static int     history_count   = 0;

static void history_push(const char* cmd) {
    if (cmd[0] == '\0') return;
    // Don't duplicate last entry
    if (history_count > 0) {
        int last = (history_count - 1) % HISTORY_SIZE;
        if (kstrcmp(history[last], cmd) == 0) return;
    }
    kstrcpy(history[history_count % HISTORY_SIZE], cmd);
    history_count++;
}

// ─────────────────────────────────────────────────
// Argument parser — splits input into argv tokens
// "echo hello world" → argv[0]="echo" argv[1]="hello" argv[2]="world"
// ─────────────────────────────────────────────────
static char* argv[MAX_ARGS];
static int   argc;
static char  parse_buf[MAX_INPUT];

static void parse_args(const char* input) {
    argc = 0;
    kstrcpy(parse_buf, input);
    char* p = parse_buf;

    while (*p && argc < MAX_ARGS) {
        // Skip spaces
        while (*p == ' ') p++;
        if (*p == '\0') break;

        argv[argc++] = p;

        // Find end of token
        while (*p && *p != ' ') p++;
        if (*p == ' ') *p++ = '\0';
    }
}

// ─────────────────────────────────────────────────
// Built-in commands
// ─────────────────────────────────────────────────
static void cmd_help() {
    print_color("\n  Vyro OS Shell Commands\n", YELLOW_ON_BLACK);
    print_color("  ─────────────────────────────────────\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    print_color("  help     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show this help menu\n");
    print_color("  clear    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Clear the screen\n");
    print_color("  echo     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Print text to screen\n");
    print_color("  version  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show OS version info\n");
    print_color("  about    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("About Vyro OS\n");
    print_color("  color    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Change terminal color (0-15)\n");
    print_color("  history  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show command history\n");
    print_color("  mem      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show memory usage\n");
    print_color("  sysinfo  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Full system dashboard\n");
    print_color("  tasks    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Run multitasking demo\n");
    print_color("  ps       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List processes\n");
    print_color("  syscall  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Demo system calls (int 0x80)\n");
    print_color("  usermode ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Drop to ring 3 and back\n");
    print_color("  exec     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Load & run an ELF64 binary\n");
    print_color("  pci      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List PCI devices\n");
    print_color("  net      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show network config\n");
    print_color("  ping     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Build & validate ICMP packet\n");
    print_color("  disk     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show ATA disk info\n");
    print_color("  diskwrite", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print(" Write text to a sector\n");
    print_color("  diskread ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Read a sector\n");
    print_color("  usb      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show USB controller info\n");
    print_color("  beep     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Beep <freq> <ms>\n");
    print_color("  play     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Play a musical scale\n");
    print_color("  gui      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Launch graphical desktop\n");
    print_color("  whoami   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current user\n");
    print_color("  login    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("login <user> <pass>\n");
    print_color("  logout   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Log out to guest\n");
    print_color("  useradd  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Add user (admin only)\n");
    print_color("  users    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List user accounts\n");
    print_color("  sha256   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Hash text with SHA-256\n");
    print_color("  vyropkg  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Package manager\n");
    print_color("  cpuinfo  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show CPU cores (ACPI)\n");
    print_color("  shutdown ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Power off the machine\n");
    print_color("  uptime   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show system uptime\n");
    print_color("  date     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current date & time\n");
    print_color("  time     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current time\n");
    print_color("  ls       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List directory contents\n");
    print_color("  pwd      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Print working directory\n");
    print_color("  cd       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Change directory\n");
    print_color("  mkdir    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Create directory\n");
    print_color("  touch    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Create empty file\n");
    print_color("  write    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Write text to a file\n");
    print_color("  cat      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show file contents\n");
    print_color("  rm       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Remove file or directory\n");
    print_color("  tree     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show filesystem tree\n");
    print_color("  sleep    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Sleep N milliseconds\n");
    print_color("  reboot   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Reboot the system\n");
    print_color("  ─────────────────────────────────────\n\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
}

static void cmd_clear() {
    screen_clear(WHITE_ON_BLACK);
    // Reprint minimal header after clear
    print_color("  Vyro OS v0.6.0  |  64-bit  |  x86_64\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

static void cmd_echo() {
    print_char('\n');
    for (int i = 1; i < argc; i++) {
        print(argv[i]);
        if (i < argc - 1) print_char(' ');
    }
    print("\n\n");
}

static void cmd_version() {
    print_color("\n  Vyro OS\n", CYAN_ON_BLACK);
    print("  Version   : 0.6.0\n");
    print("  Phase     : 6 (Interactive Shell)\n");
    print("  Arch      : x86_64 (64-bit)\n");
    print("  Kernel    : Custom (no Linux)\n");
    print("  Language  : NASM Assembly + C\n");
    print("  License   : MIT\n");
    print("  Budget    : $0\n\n");
}

static void cmd_about() {
    print_color("\n  About Vyro OS\n", CYAN_ON_BLACK);
    print("  Built from scratch — no Linux, no BSD, no shortcuts.\n");
    print("  Every line of code written by hand.\n");
    print("  Bootloader -> Protected Mode -> Long Mode -> Kernel -> Shell\n\n");
}

static void cmd_history() {
    print_char('\n');
    if (history_count == 0) {
        print_color("  No history yet.\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
        return;
    }
    int start = history_count > HISTORY_SIZE ? history_count - HISTORY_SIZE : 0;
    int n = 1;
    for (int i = start; i < history_count; i++) {
        print_color("  ", WHITE_ON_BLACK);
        print_int(n++);
        print("  ");
        print(history[i % HISTORY_SIZE]);
        print_char('\n');
    }
    print_char('\n');
}

static void cmd_color() {
    if (argc < 2) {
        print_color("\n  Usage: color <0-15>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Parse number from argv[1]
    int n = 0;
    const char* p = argv[1];
    while (*p >= '0' && *p <= '9') n = n * 10 + (*p++ - '0');
    if (n < 0 || n > 15) {
        print_color("\n  Color must be 0-15\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    screen_set_color(MAKE_COLOR(n, COLOR_BLACK));
    print("\n  Color changed.\n\n");
    screen_set_color(WHITE_ON_BLACK);
}

static void cmd_mem() {
    uint32_t total_pages = pmm_total_pages();
    uint32_t used_pages  = pmm_used_pages();
    uint32_t free_pages  = pmm_free_pages();
    uint64_t heap_u      = heap_used();
    uint64_t heap_t      = heap_total();

    print_color("\n  Physical Memory\n", YELLOW_ON_BLACK);
    print("  Total pages : "); print_int(total_pages);
    print(" ("); print_int(total_pages * 4); print(" KB)\n");
    print("  Used pages  : "); print_int(used_pages);
    print(" ("); print_int(used_pages * 4); print(" KB)\n");
    print("  Free pages  : "); print_int(free_pages);
    print(" ("); print_int(free_pages * 4); print(" KB)\n");

    print_color("\n  Heap Memory\n", YELLOW_ON_BLACK);
    print("  Total : "); print_int(heap_t / 1024); print(" KB\n");
    print("  Used  : "); print_int(heap_u); print(" bytes\n");
    print("  Free  : "); print_int((heap_t - heap_u) / 1024); print(" KB\n");

    print_color("\n  Memory Map\n", YELLOW_ON_BLACK);
    print("  0x000000 - 0x00FFFF  Bootloader + page tables\n");
    print("  0x010000 - 0x017FFF  Kernel binary\n");
    print("  0x100000 - 0x1FFFFF  PMM bitmap\n");
    print("  0x200000 - 0x4FFFFF  PMM managed pages\n");
    print("  0x500000 - 0xCFFFFF  Heap (8MB)\n\n");
}

// Print a 2-digit zero-padded number
static void print_2d(uint8_t n) {
    print_char('0' + (n / 10));
    print_char('0' + (n % 10));
}

static const char* month_names[] = {
    "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
};

static void cmd_time() {
    rtc_time_t t;
    rtc_read(&t);
    print("\n  ");
    print_2d(t.hour);   print_char(':');
    print_2d(t.minute); print_char(':');
    print_2d(t.second);
    print(" (UTC)\n\n");
}

static void cmd_date() {
    rtc_time_t t;
    rtc_read(&t);
    print("\n  ");
    if (t.month >= 1 && t.month <= 12) print(month_names[t.month]);
    print_char(' ');
    print_int(t.day);
    print(", ");
    print_int(t.year);
    print("  ");
    print_2d(t.hour);   print_char(':');
    print_2d(t.minute); print_char(':');
    print_2d(t.second);
    print(" UTC\n\n");
}

static void cmd_uptime() {
    uint64_t secs  = timer_uptime_seconds();
    uint64_t ms    = timer_uptime_ms();
    uint64_t ticks = timer_ticks();

    uint64_t hours = secs / 3600;
    uint64_t mins  = (secs % 3600) / 60;
    uint64_t s     = secs % 60;

    print_color("\n  System Uptime\n", YELLOW_ON_BLACK);
    print("  ");
    print_int(hours); print("h ");
    print_int(mins);  print("m ");
    print_int(s);     print("s\n");
    print("  Total : "); print_int(ms);    print(" ms\n");
    print("  Ticks : "); print_int(ticks); print(" (@100 Hz)\n\n");
}

static void cmd_sleep() {
    if (argc < 2) {
        print_color("\n  Usage: sleep <milliseconds>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t ms = 0;
    const char* p = argv[1];
    while (*p >= '0' && *p <= '9') ms = ms * 10 + (*p++ - '0');

    print("\n  Sleeping for ");
    print_int(ms);
    print(" ms...");
    sleep_ms(ms);
    print_color(" done.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// Filesystem commands — track current working directory
// ─────────────────────────────────────────────────
static vfs_node_t* cwd = 0;

static void fs_ensure() {
    if (!cwd) cwd = vfs_root();
}

static void cmd_pwd() {
    fs_ensure();
    char path[256];
    vfs_full_path(cwd, path, sizeof(path));
    print("\n  ");
    print(path);
    print("\n\n");
}

static void cmd_ls() {
    fs_ensure();
    vfs_node_t* dir = cwd;

    // Optional argument: ls <dir>
    if (argc >= 2) {
        vfs_node_t* target = vfs_find(cwd, argv[1]);
        if (!target) {
            print_color("\n  ls: no such directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            print(argv[1]); print("\n\n");
            return;
        }
        dir = target;
    }

    print_char('\n');
    vfs_node_t* cur = dir->first_child;
    if (!cur) {
        print_color("  (empty)\n\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        return;
    }
    while (cur) {
        if (cur->type == VFS_DIRECTORY) {
            print_color("  ", WHITE_ON_BLACK);
            print_color(cur->name, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            print_color("/\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
        } else {
            print("  ");
            print(cur->name);
            print("  (");
            print_int(cur->size);
            print(" bytes)\n");
        }
        cur = cur->next_sibling;
    }
    print_char('\n');
}

static void cmd_cd() {
    fs_ensure();
    if (argc < 2) { cwd = vfs_root(); return; }

    vfs_node_t* target = vfs_find(cwd, argv[1]);
    if (!target) {
        print_color("\n  cd: no such directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    if (target->type != VFS_DIRECTORY) {
        print_color("\n  cd: not a directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    cwd = target;
}

static void cmd_mkdir() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: mkdir <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_create(cwd, argv[1], VFS_DIRECTORY)) {
        print_color("\n  mkdir: cannot create '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("' (exists?)\n\n");
    }
}

static void cmd_touch() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: touch <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_create(cwd, argv[1], VFS_FILE)) {
        print_color("\n  touch: cannot create '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("' (exists?)\n\n");
    }
}

static void cmd_write() {
    fs_ensure();
    if (argc < 3) {
        print_color("\n  Usage: write <file> <text...>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    vfs_node_t* file = vfs_find(cwd, argv[1]);
    if (!file) {
        // Auto-create the file
        file = vfs_create(cwd, argv[1], VFS_FILE);
        if (!file) {
            print_color("\n  write: cannot create file\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            return;
        }
    }
    if (file->type != VFS_FILE) {
        print_color("\n  write: not a file\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    // Join argv[2..] into one string buffer
    static char buf[1024];
    int pos = 0;
    for (int i = 2; i < argc && pos < 1020; i++) {
        const char* w = argv[i];
        for (int j = 0; w[j] && pos < 1020; j++) buf[pos++] = w[j];
        if (i < argc - 1 && pos < 1020) buf[pos++] = ' ';
    }
    buf[pos] = '\0';

    vfs_write(file, buf);
}

static void cmd_cat() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: cat <file>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    vfs_node_t* file = vfs_find(cwd, argv[1]);
    if (!file) {
        print_color("\n  cat: no such file: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    if (file->type != VFS_FILE) {
        print_color("\n  cat: is a directory\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print("\n  ");
    print(vfs_read(file));
    print("\n\n");
}

static void cmd_rm() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: rm <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_remove(cwd, argv[1])) {
        print_color("\n  rm: no such file or directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
    }
}

// Recursive tree printer
static void tree_print(vfs_node_t* node, int depth) {
    vfs_node_t* cur = node->first_child;
    while (cur) {
        for (int i = 0; i < depth; i++) print("  ");
        print("  ");
        if (cur->type == VFS_DIRECTORY) {
            print_color(cur->name, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            print_color("/\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            tree_print(cur, depth + 1);
        } else {
            print(cur->name);
            print_char('\n');
        }
        cur = cur->next_sibling;
    }
}

static void cmd_tree() {
    fs_ensure();
    print_color("\n  /\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
    tree_print(vfs_root(), 0);
    print_char('\n');
}

// ─────────────────────────────────────────────────
// Multitasking demo tasks
// Each prints its label a few times, yielding between,
// so you can see the round-robin interleaving.
// ─────────────────────────────────────────────────
static void demo_task_a() {
    for (int i = 0; i < 5; i++) {
        print_color("[A]", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void demo_task_b() {
    for (int i = 0; i < 5; i++) {
        print_color("[B]", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void demo_task_c() {
    for (int i = 0; i < 5; i++) {
        print_color("[C]", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void cmd_tasks() {
    print_color("\n  Spawning 3 cooperative tasks...\n  Output: ", WHITE_ON_BLACK);

    tasking_init();
    task_create("task-a", demo_task_a);
    task_create("task-b", demo_task_b);
    task_create("task-c", demo_task_c);

    // Run scheduler — returns when all tasks finish
    task_run_all();

    print_color("\n  All tasks finished.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_ps() {
    print_color("\n  PID  NAME            STATE\n", YELLOW_ON_BLACK);
    print_color("  ---  --------------  --------\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    print("  1    kernel/shell    RUNNING\n");

    uint32_t n = task_count();
    if (n == 0) {
        print_color("  (no background tasks)\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    }
    print_char('\n');
}

// ─────────────────────────────────────────────────
// Ring-3 user program. Runs UNPRIVILEGED. Its only way
// to talk to the kernel is int 0x80. No direct hardware,
// no privileged instructions allowed.
// ─────────────────────────────────────────────────
extern void enter_user_mode(uint64_t entry, uint64_t user_stack);
static uint8_t user_stack[8192] __attribute__((aligned(16)));

static void user_program() {
    // SYS_WRITE — print a message from ring 3
    __asm__ volatile("int $0x80" : : "a"(SYS_WRITE),
                     "D"("  [ring3] Hello from user mode!\n") : "memory");

    // SYS_GETPID
    uint64_t pid;
    __asm__ volatile("int $0x80" : "=a"(pid) : "a"(SYS_GETPID), "D"(0));
    __asm__ volatile("int $0x80" : : "a"(SYS_WRITE),
                     "D"("  [ring3] Made syscalls without crashing.\n") : "memory");

    // SYS_EXIT — return to the kernel (does not come back)
    __asm__ volatile("int $0x80" : : "a"(SYS_EXIT), "D"(0));

    // Should never reach here
    for (;;) {}
}

// Print a hex byte (2 digits)
static void print_hex2(uint8_t b) {
    const char* h = "0123456789ABCDEF";
    print_char(h[b >> 4]);
    print_char(h[b & 0xF]);
}

static uint32_t parse_uint(const char* p) {
    uint32_t n = 0;
    while (*p >= '0' && *p <= '9') n = n * 10 + (*p++ - '0');
    return n;
}

static void cmd_disk() {
    print_color("\n  ATA Disk (primary slave)\n", YELLOW_ON_BLACK);
    if (ata_init()) {
        print_color("  Status : present, ATA, LBA28\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print("  Sector : 512 bytes\n");
        print("  Use 'diskwrite <lba> <text>' and 'diskread <lba>'\n\n");
    } else {
        print_color("  Status : no disk detected\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_diskwrite() {
    if (argc < 3) {
        print_color("\n  Usage: diskwrite <lba> <text>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t lba = parse_uint(argv[1]);

    static uint8_t sector[512];
    for (int i = 0; i < 512; i++) sector[i] = 0;

    // Join argv[2..] into the sector buffer
    int pos = 0;
    for (int i = 2; i < argc && pos < 510; i++) {
        const char* w = argv[i];
        for (int j = 0; w[j] && pos < 510; j++) sector[pos++] = (uint8_t)w[j];
        if (i < argc - 1 && pos < 510) sector[pos++] = ' ';
    }

    if (ata_write_sector(lba, sector) == 0) {
        print("\n  Wrote ");
        print_int(pos);
        print(" bytes to LBA ");
        print_int(lba);
        print_color("  [persisted to disk]\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    } else {
        print_color("\n  diskwrite: write failed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_diskread() {
    if (argc < 2) {
        print_color("\n  Usage: diskread <lba>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t lba = parse_uint(argv[1]);

    static uint8_t sector[512];
    if (ata_read_sector(lba, sector) != 0) {
        print_color("\n  diskread: read failed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("\n  LBA ");
    print_int(lba);
    print(" contents: \"");
    // Print as text up to first NUL
    for (int i = 0; i < 512 && sector[i]; i++) print_char((char)sector[i]);
    print("\"\n\n");
}

static void cmd_browser() {
    print_color("\n  Launching VyroBrowser... (ESC to exit)\n", YELLOW_ON_BLACK);
    sleep_ms(300);
    html_render(HOME_PAGE);
    screen_clear(WHITE_ON_BLACK);
    print_color("  Exited VyroBrowser.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_dmesg() {
    print_color("\n  Kernel Log\n", YELLOW_ON_BLACK);
    int n = klog_count();
    for (int i = 0; i < n; i++) {
        print_color("  [", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        print_int(i);
        print_color("] ", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        print(klog_get(i));
        print_char('\n');
    }
    print_char('\n');
}

static void cmd_peek() {
    if (argc < 2) {
        print_color("\n  Usage: peek <hexaddr>   e.g. peek b8000\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Parse hex address
    uint64_t addr = 0;
    const char* p = argv[1];
    if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) p += 2;
    while (*p) {
        char c = *p++;
        uint8_t v;
        if (c >= '0' && c <= '9') v = c - '0';
        else if (c >= 'a' && c <= 'f') v = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') v = c - 'A' + 10;
        else break;
        addr = (addr << 4) | v;
    }

    volatile uint8_t* mem = (volatile uint8_t*) addr;
    print("\n  Memory at ");
    print_hex(addr);
    print(":\n");
    for (int row = 0; row < 4; row++) {
        print("  ");
        print_hex(addr + row * 16);
        print("  ");
        for (int col = 0; col < 16; col++) {
            uint8_t b = mem[row * 16 + col];
            const char* h = "0123456789ABCDEF";
            print_char(h[b >> 4]); print_char(h[b & 0xF]); print_char(' ');
        }
        print_char('\n');
    }
    print_char('\n');
}

static void cmd_prof() {
    print_color("\n  Profiler / Performance\n", YELLOW_ON_BLACK);
    print("  Timer ticks   : "); print_int(timer_ticks());     print("\n");
    print("  Uptime (ms)   : "); print_int(timer_uptime_ms()); print("\n");
    print("  Timer freq    : 100 Hz\n");
    print("  Heap used     : "); print_int(heap_used());       print(" bytes\n");
    print("  Phys pages    : "); print_int(pmm_used_pages());
    print(" used / "); print_int(pmm_total_pages()); print("\n");
    print("  CPU cores     : "); print_int(cpu_count());       print("\n\n");
}

static void cmd_cpuinfo() {
    print_color("\n  CPU Information (via ACPI MADT)\n", YELLOW_ON_BLACK);

    print("  ACPI       : ");
    if (acpi_found()) print_color("found\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    else print_color("not found\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));

    print("  CPU cores  : ");
    print_int(cpu_count());
    print_char('\n');

    print("  LAPIC addr : ");
    print_hex(lapic_address());
    print_char('\n');

    print("  APIC IDs   : ");
    for (uint32_t i = 0; i < cpu_count(); i++) {
        print_int(cpu_apic_id(i));
        if (i < cpu_count() - 1) print(", ");
    }
    print("\n\n");
}

static void cmd_vyropkg() {
    if (argc < 2) {
        print_color("\n  vyropkg - Vyro OS package manager\n", YELLOW_ON_BLACK);
        print("  Usage:\n");
        print("    vyropkg list             list available packages\n");
        print("    vyropkg installed        list installed packages\n");
        print("    vyropkg install <name>   install a package + deps\n");
        print("    vyropkg remove <name>    remove a package\n");
        print("    vyropkg search <name>    find a package\n\n");
        return;
    }

    if (kstrcmp(argv[1], "list") == 0) {
        int n; package_t* r = pkg_repo(&n);
        print_color("\n  Available packages\n", YELLOW_ON_BLACK);
        for (int i = 0; i < n; i++) {
            print(r[i].installed ? "  [x] " : "  [ ] ");
            print(r[i].name);
            print("  v"); print(r[i].version);
            print("  - "); print(r[i].desc);
            print_char('\n');
        }
        print_char('\n');

    } else if (kstrcmp(argv[1], "installed") == 0) {
        int n; package_t* r = pkg_repo(&n);
        print_color("\n  Installed packages\n", YELLOW_ON_BLACK);
        int any = 0;
        for (int i = 0; i < n; i++) {
            if (r[i].installed) {
                print("  "); print(r[i].name); print(" v"); print(r[i].version); print_char('\n');
                any = 1;
            }
        }
        if (!any) print_color("  (none installed)\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        print_char('\n');

    } else if (kstrcmp(argv[1], "install") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg install <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        print_color("\n  Resolving dependencies for '", WHITE_ON_BLACK);
        print(argv[2]); print("'...\n");
        int r = pkg_install(argv[2]);
        if (r < 0) {
            print_color("  vyropkg: package not found\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        } else if (r == 0) {
            print_color("  already installed.\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
        } else {
            print_color("  Done. ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
            print_int(r); print(" package(s) installed (see /bin).\n\n");
        }

    } else if (kstrcmp(argv[1], "remove") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg remove <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        if (pkg_remove(argv[2]) == 0) {
            print_color("\n  Removed '", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
            print(argv[2]); print("'.\n\n");
        } else {
            print_color("\n  vyropkg: not installed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        }

    } else if (kstrcmp(argv[1], "search") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg search <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        package_t* p = pkg_find(argv[2]);
        if (p) {
            print("\n  "); print(p->name); print(" v"); print(p->version);
            print("\n  "); print(p->desc); print("\n\n");
        } else {
            print_color("\n  No package named '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            print(argv[2]); print("'\n\n");
        }
    } else {
        print_color("\n  vyropkg: unknown subcommand\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_whoami() {
    print("\n  ");
    print(current_user());
    if (current_is_admin()) print_color("  (admin)\n\n", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
    else print_color("  (standard user)\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

static void cmd_login() {
    if (argc < 3) {
        print_color("\n  Usage: login <user> <password>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int r = auth_login(argv[1], argv[2]);
    if (r == 0) {
        print_color("\n  Login successful. Welcome, ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print(current_user());
        print(".\n\n");
    } else if (r == -1) {
        print_color("\n  login: incorrect password\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    } else {
        print_color("\n  login: no such user\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_logout() {
    auth_logout();
    print_color("\n  Logged out. Now: ", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print(current_user());
    print("\n\n");
}

static void cmd_useradd() {
    if (!current_is_admin()) {
        print_color("\n  useradd: permission denied (admin only)\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (argc < 3) {
        print_color("\n  Usage: useradd <user> <password>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (user_add(argv[1], argv[2], 0) == 0) {
        print_color("\n  User '", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print(argv[1]); print("' created.\n\n");
    } else {
        print_color("\n  useradd: failed (exists or full)\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_users() {
    user_t* list;
    int n = user_list(&list);
    print_color("\n  USERS\n", YELLOW_ON_BLACK);
    print_color("  UID   NAME            ROLE\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    for (int i = 0; i < n; i++) {
        print("  ");
        print_int(list[i].uid);
        print("  ");
        print(list[i].name);
        // pad
        int pad = 16 - (int)0; (void)pad;
        print("   ");
        if (list[i].is_admin) print_color("admin\n", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
        else print("user\n");
    }
    print_char('\n');
}

static void cmd_sha256() {
    if (argc < 2) {
        print_color("\n  Usage: sha256 <text>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Hash argv[1] (single token)
    const char* s = argv[1];
    int len = 0; while (s[len]) len++;
    uint8_t digest[32];
    char hex[65];
    sha256((const uint8_t*)s, len, digest);
    sha256_hex(digest, hex);
    print("\n  sha256(\"");
    print(s);
    print("\") =\n  ");
    print_color(hex, MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print("\n\n");
}

static void cmd_gui() {
    print_color("\n  Launching GUI desktop... (ESC to return)\n", YELLOW_ON_BLACK);
    sleep_ms(300);
    gui_run();
    // Returning to text mode: clear and redraw a minimal header
    screen_clear(WHITE_ON_BLACK);
    print_color("  Exited GUI. Back to shell.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_beep() {
    uint32_t freq = 440;   // default A4
    uint32_t dur  = 200;
    if (argc >= 2) freq = parse_uint(argv[1]);
    if (argc >= 3) dur  = parse_uint(argv[2]);

    print("\n  Beep: ");
    print_int(freq);
    print(" Hz for ");
    print_int(dur);
    print(" ms\n\n");

    beep(freq, dur);
}

static void cmd_play() {
    print_color("\n  Playing scale (C major)...\n\n", YELLOW_ON_BLACK);

    int notes[]    = { NOTE_C4, NOTE_D4, NOTE_E4, NOTE_F4,
                       NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5 };
    const char* nm[] = { "C", "D", "E", "F", "G", "A", "B", "C" };

    for (int i = 0; i < 8; i++) {
        print("  ");
        print(nm[i]);
        beep((uint32_t)notes[i], 200);
        sleep_ms(40);
    }
    print("\n\n");
}

static void cmd_usb() {
    print_color("\n  USB Subsystem\n", YELLOW_ON_BLACK);

    pci_device_t* c = pci_find_class(0x0C, 0x03);
    if (!c) {
        print_color("  No USB host controller found.\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("  Controller : ");
    print(usb_controller_type());
    print_char('\n');

    print("  PCI        : ");
    print_hex(c->vendor_id); print(":"); print_hex(c->device_id);
    print("  (bus "); print_int(c->bus); print(" slot "); print_int(c->slot); print(")\n");

    print("  prog-if    : ");
    print_hex(c->prog_if);
    print_char('\n');

    print("  IRQ        : ");
    print_int(c->irq_line);
    print_char('\n');

    print_color("\n  Descriptor sizes: device=18B  setup=8B\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_color("  Controller detected & identified via PCI.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

// Parse "a.b.c.d" into out[4]. Returns 1 on success.
static int parse_ipv4(const char* s, uint8_t out[4]) {
    int part = 0, val = 0, digits = 0;
    for (const char* p = s; ; p++) {
        if (*p >= '0' && *p <= '9') {
            val = val * 10 + (*p - '0');
            if (val > 255) return 0;
            digits++;
        } else if (*p == '.' || *p == '\0') {
            if (!digits || part > 3) return 0;
            out[part++] = (uint8_t)val;
            if (*p == '\0') return part == 4;
            val = 0; digits = 0;
        } else return 0;
    }
}

static void print_ip(const uint8_t* ip);

// realping <ip>: send ICMP echo via RTL8139 and wait for a reply, print RTT.
static void cmd_realping() {
    uint8_t dst_ip[4] = { 10, 0, 2, 2 };   // default: QEMU SLIRP gateway
    if (argc >= 2 && !parse_ipv4(argv[1], dst_ip)) {
        print_color("\n  Usage: realping <a.b.c.d>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print_color("\n  PING ", YELLOW_ON_BLACK);
    print_ip(dst_ip); print(" via RTL8139\n");

    // Resolve destination MAC via ARP (gateway if dst is off-link — but for now
    // we ARP the dst directly; QEMU SLIRP answers for both LAN and 10.0.2.2).
    uint8_t dst_mac[6];
    if (!arp_resolve(dst_ip, 1000, dst_mac)) {
        print_color("  ARP failed (no reply in 1s) — falling back to broadcast MAC\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        for (int i = 0; i < 6; i++) dst_mac[i] = 0xFF;
    } else {
        print("  ARP: ");
        for (int i = 0; i < 6; i++) {
            print_hex2(dst_mac[i]);
            if (i < 5) print_char(':');
        }
        print_char('\n');
    }

    static uint8_t frame[64];
    for (int i = 0; i < 64; i++) frame[i] = 0;

    eth_header_t* eh = (eth_header_t*) frame;
    for (int i = 0; i < 6; i++) { eh->dst[i] = dst_mac[i]; eh->src[i] = net_mac()[i]; }
    eh->ethertype = htons(ETHERTYPE_IPV4);

    ipv4_header_t* ip = (ipv4_header_t*)(frame + sizeof(eth_header_t));
    ip->ver_ihl   = 0x45;
    ip->total_len = htons(sizeof(ipv4_header_t) + sizeof(icmp_header_t));
    ip->ttl       = 64;
    ip->protocol  = IP_PROTO_ICMP;
    for (int i = 0; i < 4; i++) ip->src[i] = net_ip()[i];
    for (int i = 0; i < 4; i++) ip->dst[i] = dst_ip[i];
    ip->checksum  = 0;
    ip->checksum  = htons(net_checksum(ip, sizeof(ipv4_header_t)));

    static uint16_t ping_seq = 0;
    uint16_t my_id  = 0xBEEF;
    uint16_t my_seq = ++ping_seq;

    icmp_header_t* icmp = (icmp_header_t*)((uint8_t*)ip + sizeof(ipv4_header_t));
    icmp->type = ICMP_ECHO_REQUEST; icmp->code = 0;
    icmp->id   = htons(my_id);
    icmp->seq  = htons(my_seq);
    icmp->checksum = 0;
    icmp->checksum = htons(net_checksum(icmp, sizeof(icmp_header_t)));

    uint64_t t0 = timer_uptime_ms();
    int total = sizeof(eth_header_t) + sizeof(ipv4_header_t) + sizeof(icmp_header_t);
    int sent  = rtl8139_send(frame, (uint16_t)total);
    if (sent < 0) {
        print_color("  ERROR: NIC not initialised (no RTL8139 found)\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    // Wait up to 2s for a matching ICMP echo reply.
    uint64_t deadline = t0 + 2000;
    while (timer_uptime_ms() < deadline) {
        netio_pkt_t in;
        while (net_io_poll(&in)) {
            if (arp_input(in.data, in.len)) continue;       // ARP consumed it
            if (in.len < 14 + 20 + 8) continue;
            if (!(in.data[12] == 0x08 && in.data[13] == 0x00)) continue;
            const uint8_t* rip  = in.data + 14;
            if ((rip[0] & 0xF0) != 0x40)        continue;          // IPv4
            uint8_t ihl = (rip[0] & 0x0F) * 4;
            if (rip[9] != IP_PROTO_ICMP)        continue;
            // Source IP must match what we pinged
            int src_match = 1;
            for (int i = 0; i < 4; i++) if (rip[12+i] != dst_ip[i]) { src_match = 0; break; }
            if (!src_match) continue;
            const uint8_t* ricmp = rip + ihl;
            if (ricmp[0] != 0) continue;                            // 0 = echo reply
            uint16_t r_id  = ((uint16_t)ricmp[4] << 8) | ricmp[5];
            uint16_t r_seq = ((uint16_t)ricmp[6] << 8) | ricmp[7];
            if (r_id != my_id || r_seq != my_seq) continue;

            uint64_t rtt = timer_uptime_ms() - t0;
            print("  Reply from "); print_ip(dst_ip);
            print(": seq="); print_int(my_seq);
            print(" ttl=");  print_int(rip[8]);
            print(" time="); print_int((int)rtt); print(" ms\n");
            print_color("  1 packet transmitted, 1 received, 0% loss\n\n",
                        MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
            return;
        }
        __asm__ volatile("hlt");
    }
    print_color("  Request timed out (2s)\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    print("  TX/RX: "); print_int(net_io_tx_count()); print(" / ");
    print_int(net_io_rx_count()); print("\n\n");
}

static void print_ip(const uint8_t* ip) {
    for (int i = 0; i < 4; i++) {
        print_int(ip[i]);
        if (i < 3) print_char('.');
    }
}

static void cmd_dhcp() {
    print_color("\n  Sending DHCPDISCOVER over RTL8139...\n", YELLOW_ON_BLACK);
    if (dhcp_real_run(2000)) {
        print_color("  DHCP success!\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print("  Offered IP : "); print_ip(dhcp_real_ip());  print_char('\n');
        print("  Gateway    : "); print_ip(dhcp_real_gw());  print_char('\n');
        print("  DNS server : "); print_ip(dhcp_real_dns()); print("\n\n");
    } else {
        print_color("  DHCP timeout (no OFFER received in 2s).\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print("  NIC TX count: "); print_int(net_io_tx_count()); print_char('\n');
        print("  NIC RX count: "); print_int(net_io_rx_count()); print("\n\n");
    }
}

static void cmd_nslookup() {
    if (argc < 2) {
        print_color("\n  Usage: nslookup <hostname>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Use DHCP-learned DNS if we have one; else QEMU default 10.0.2.3
    uint8_t dns_ip[4] = { 10, 0, 2, 3 };
    const uint8_t* learned = dhcp_real_dns();
    int has = 0; for (int i = 0; i < 4; i++) if (learned[i]) has = 1;
    if (has) for (int i = 0; i < 4; i++) dns_ip[i] = learned[i];

    print_color("\n  Resolving '", YELLOW_ON_BLACK);
    print(argv[1]); print("' via DNS server "); print_ip(dns_ip); print("...\n");
    uint8_t out[4] = {0};
    if (dns_real_resolve(argv[1], dns_ip, 2000, out)) {
        print_color("  Resolved: ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print(argv[1]); print(" -> "); print_ip(out); print("\n\n");
    } else {
        print_color("  Timed out (no DNS response in 2s).\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print("  NIC TX/RX: "); print_int(net_io_tx_count()); print(" / ");
        print_int(net_io_rx_count()); print("\n\n");
    }
}

static void cmd_pci() {
    print_color("\n  PCI Devices\n", YELLOW_ON_BLACK);
    print_color("  BUS:SLOT  VENDOR:DEVICE  CLASS  DESC\n",
                MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    uint32_t n = pci_device_count();
    for (uint32_t i = 0; i < n; i++) {
        pci_device_t* d = pci_get_device(i);
        print("  ");
        print_hex2(d->bus); print(":"); print_hex2(d->slot);
        print("     ");
        print_hex((d->vendor_id)); print(":"); print_hex(d->device_id);
        print("  ");
        print_hex2(d->class_id);
        print("    ");
        if (d->class_id == 0x02)      print("Network controller");
        else if (d->class_id == 0x01) print("Storage controller");
        else if (d->class_id == 0x03) print("Display controller");
        else if (d->class_id == 0x06) print("Bridge");
        else                          print("Device");
        print_char('\n');
    }
    print_char('\n');
}

static int udp_listener_count;
static void udp_print_listener(uint16_t port, void* user) {
    (void)user;
    print("  port "); print_int(port); print_char('\n');
    udp_listener_count++;
}

static const char* tcp_state_name(int s) {
    switch (s) {
    case TCP_CLOSED:        return "CLOSED";
    case TCP_LISTEN:        return "LISTEN";
    case TCP_SYN_SENT:      return "SYN_SENT";
    case TCP_SYN_RECEIVED:  return "SYN_RECEIVED";
    case TCP_ESTABLISHED:   return "ESTABLISHED";
    case TCP_FIN_WAIT_1:    return "FIN_WAIT_1";
    case TCP_FIN_WAIT_2:    return "FIN_WAIT_2";
    case TCP_CLOSE_WAIT:    return "CLOSE_WAIT";
    case TCP_LAST_ACK:      return "LAST_ACK";
    case TCP_TIME_WAIT:     return "TIME_WAIT";
    default:                return "?";
    }
}

static int tcp_dump_count;
static void tcp_dump_one(int id, const tcp_tcb_t* t, void* user) {
    (void)user;
    print("  ["); print_int(id); print("] ");
    print(tcp_state_name(t->state));
    print("  local:"); print_int(t->local_port);
    print("  remote:");
    for (int i = 0; i < 4; i++) {
        print_int(t->remote_ip[i]);
        if (i < 3) print_char('.');
    }
    print_char(':'); print_int(t->remote_port);
    print_char('\n');
    tcp_dump_count++;
}

static void cmd_tcp() {
    print_color("\n  TCP connections\n", YELLOW_ON_BLACK);
    tcp_dump_count = 0;
    tcp_for_each(tcp_dump_one, 0);
    if (!tcp_dump_count) print("  (none)\n");
    print_char('\n');
}

static int parse_int_safe(const char* s, int* out) {
    int v = 0; int any = 0;
    for (const char* p = s; *p; p++) {
        if (*p < '0' || *p > '9') return 0;
        v = v * 10 + (*p - '0');
        any = 1;
    }
    if (!any) return 0;
    *out = v; return 1;
}

static void cmd_tcpconnect() {
    if (argc < 3) {
        print_color("\n  Usage: tcpconnect <a.b.c.d> <port>\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint8_t ip[4];
    int port_int;
    if (!parse_ipv4(argv[1], ip) || !parse_int_safe(argv[2], &port_int) ||
        port_int <= 0 || port_int > 65535) {
        print_color("\n  Bad ip or port\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print_color("\n  TCP connect ", YELLOW_ON_BLACK);
    print_ip(ip); print_char(':'); print_int(port_int); print_char('\n');
    int id = tcp_connect(ip, (uint16_t)port_int);
    if (id < 0) {
        print_color("  tcp_connect failed (no free TCB)\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Drive the pump until we leave SYN_SENT or time out.
    for (int i = 0; i < 80; i++) {
        net_pump_run(100);
        int s = tcp_state(id);
        if (s != TCP_SYN_SENT) break;
    }
    int s = tcp_state(id);
    print("  Result: "); print(tcp_state_name(s));
    if (s == TCP_ESTABLISHED) {
        print_color("  (handshake OK)\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        tcp_close(id);
        net_pump_run(500);
    } else {
        print_color("  (no connection)\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
    print_char('\n');
}

static uint16_t mini_strlen(const char* s) {
    uint16_t n = 0; while (s[n]) n++; return n;
}

static void cmd_tcpsend() {
    if (argc < 3) {
        print_color("\n  Usage: tcpsend <conn_id> <text>\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int id;
    if (!parse_int_safe(argv[1], &id)) {
        print_color("\n  Bad id\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint16_t total = 0;
    for (int i = 2; i < argc; i++) {
        uint16_t n = mini_strlen(argv[i]);
        int sent = tcp_send(id, (const uint8_t*)argv[i], n);
        if (sent < 0) {
            print_color("\n  tcp_send: not ESTABLISHED or bad id\n\n",
                        MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            return;
        }
        total += (uint16_t)sent;
        if (i + 1 < argc) {
            uint8_t sp = ' ';
            int s2 = tcp_send(id, &sp, 1);
            if (s2 > 0) total++;
        }
    }
    uint8_t nl = '\n';
    tcp_send(id, &nl, 1);
    print_color("\n  Sent ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_int(total + 1); print(" bytes\n\n");
}

static void cmd_tcprecv() {
    if (argc < 2) {
        print_color("\n  Usage: tcprecv <conn_id> [wait_ms]\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int id, wait_ms = 1000;
    if (!parse_int_safe(argv[1], &id)) {
        print_color("\n  Bad id\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (argc >= 3) parse_int_safe(argv[2], &wait_ms);

    static uint8_t buf[1024];
    int total = 0;
    int slices = wait_ms / 100;
    if (slices < 1) slices = 1;
    for (int s = 0; s < slices; s++) {
        net_pump_run(100);
        int n = tcp_recv(id, buf, sizeof(buf) - 1);
        if (n < 0) {
            print_color("\n  tcp_recv: bad id\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            return;
        }
        if (n > 0) {
            buf[n] = 0;
            for (int i = 0; i < n; i++) print_char((char)buf[i]);
            total += n;
        }
    }
    if (total == 0) print_color("\n  (no data)\n\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    else            { print_color("\n  -- ", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
                      print_int(total); print(" bytes received --\n\n"); }
}

#include "x509.h"
#include "hkdf.h"
#include "x25519.h"

static void cmd_tlskdf() {
    print_color("\n  TLS 1.3 crypto pipeline\n", YELLOW_ON_BLACK);

    int h = hkdf_selftest();
    int x = x25519_selftest();
    print("  HMAC/HKDF selftest : ");
    print(h ? "PASS\n" : "FAIL\n");
    print("  X25519 selftest    : ");
    print(x ? "PASS\n" : "FAIL\n");

    // Demo: derive an ECDH shared secret from two static scalars.
    uint8_t alice_priv[32], bob_priv[32], alice_pub[32], bob_pub[32];
    for (int i = 0; i < 32; i++) { alice_priv[i] = (uint8_t)(0x10 + i); bob_priv[i] = (uint8_t)(0x80 ^ i); }
    x25519_base(alice_pub, alice_priv);
    x25519_base(bob_pub,   bob_priv);
    uint8_t s_ab[32], s_ba[32];
    x25519(s_ab, alice_priv, bob_pub);
    x25519(s_ba, bob_priv,   alice_pub);
    int match = 1;
    for (int i = 0; i < 32; i++) if (s_ab[i] != s_ba[i]) { match = 0; break; }
    print("  ECDH agreement     : ");
    print(match ? "PASS (a*B == b*A)\n" : "FAIL\n");

    // Demo: derive a 32-byte handshake secret via HKDF-Expand-Label
    uint8_t prk[32], out[32];
    hkdf_extract(0, 0, s_ab, 32, prk);
    tls13_hkdf_expand_label(prk, "derived", (const uint8_t*)"", 0, out, 32);
    print("  Expand-Label OK    : (32 bytes)\n");
    print_char('\n');
}

extern const uint8_t x509_testvec_der[406];

static void cmd_x509() {
    x509_cert_t c;
    if (!x509_parse(x509_testvec_der, 406, &c)) {
        print_color("\n  x509_parse FAILED\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print_color("\n  X.509 test certificate\n", YELLOW_ON_BLACK);
    print("  Subject CN : "); print(c.subject_cn); print_char('\n');
    print("  Issuer  CN : "); print(c.issuer_cn);  print_char('\n');
    print("  Not before : "); print(c.not_before); print_char('\n');
    print("  Not after  : "); print(c.not_after);  print_char('\n');
    print("  Sig alg    : "); print(x509_sig_alg_name(c.sig_alg));   print_char('\n');
    print("  PKey alg   : "); print(x509_pkey_alg_name(c.pkey_alg)); print_char('\n');
    print("  SANs ("); print_int(c.san_count); print("):\n");
    for (int i = 0; i < c.san_count; i++) {
        print("    "); print(c.san[i]); print_char('\n');
    }
    print_char('\n');
}

extern int aead_selftest(void);
static void cmd_crypto() {
    print_color("\n  Running ChaCha20-Poly1305 RFC 8439 vectors...\n", YELLOW_ON_BLACK);
    if (aead_selftest()) {
        print_color("  ChaCha20 §2.4.2  : PASS\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print_color("  Poly1305 §2.5.2  : PASS\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print_color("  AEAD §2.8.2      : PASS (seal tag + open round-trip)\n",
                    MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    } else {
        print_color("  FAILED — crypto unsafe, do not use\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
    print_char('\n');
}

static void cmd_tcplisten() {
    if (argc < 2) {
        print_color("\n  Usage: tcplisten <port>\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int port;
    if (!parse_int_safe(argv[1], &port) || port <= 0 || port > 65535) {
        print_color("\n  Bad port\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int id = tcp_listen((uint16_t)port);
    if (id < 0) {
        print_color("\n  tcp_listen failed (port taken or TCB table full)\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print_color("\n  Listening on port ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_int(port); print(" (TCB id="); print_int(id); print(")\n\n");
}

static void cmd_tcpaccept() {
    if (argc < 2) {
        print_color("\n  Usage: tcpaccept <port> [wait_ms]\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int port, wait_ms = 3000;
    if (!parse_int_safe(argv[1], &port) || port <= 0 || port > 65535) {
        print_color("\n  Bad port\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (argc >= 3) parse_int_safe(argv[2], &wait_ms);

    print_color("\n  Waiting for incoming connection on port ", YELLOW_ON_BLACK);
    print_int(port); print(" (up to "); print_int(wait_ms); print(" ms)...\n");

    int id = -1;
    int slices = wait_ms / 100;
    if (slices < 1) slices = 1;
    for (int i = 0; i < slices; i++) {
        net_pump_run(100);
        id = tcp_accept((uint16_t)port);
        if (id >= 0) break;
    }
    if (id < 0) {
        print_color("  No connection arrived\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print_color("  Accepted! conn id=", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_int(id); print_char('\n');
    print("  (state: "); print(tcp_state_name(tcp_state(id))); print(")\n\n");
}

static void cmd_udp() {
    print_color("\n  UDP listeners\n", YELLOW_ON_BLACK);
    udp_listener_count = 0;
    udp_for_each_listener(udp_print_listener, 0);
    if (!udp_listener_count) print("  (none)\n");
    print_char('\n');
}

static void cmd_net() {
    print_color("\n  Vyro OS Network Configuration\n", YELLOW_ON_BLACK);

    const uint8_t* mac = net_mac();
    print("  MAC : ");
    for (int i = 0; i < 6; i++) {
        print_hex2(mac[i]);
        if (i < 5) print_char(':');
    }
    print_char('\n');

    const uint8_t* ip = net_ip();
    print("  IP  : ");
    for (int i = 0; i < 4; i++) {
        print_int(ip[i]);
        if (i < 3) print_char('.');
    }
    print_char('\n');

    pci_device_t* nic = pci_find_network();
    print("  NIC : ");
    if (nic) {
        print_hex(nic->vendor_id); print(":"); print_hex(nic->device_id);
        print(" (IRQ "); print_int(nic->irq_line); print(")\n");
    } else {
        print_color("none detected\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
    print_char('\n');
}

// Build an ICMP echo request, run it through the stack (loopback),
// verify the checksum — demonstrates the protocol layers working.
static void cmd_ping() {
    print_color("\n  Building ICMP echo packet (loopback)...\n\n", YELLOW_ON_BLACK);

    static uint8_t packet[64];
    for (int i = 0; i < 64; i++) packet[i] = 0;

    // Ethernet header
    eth_header_t* eth = (eth_header_t*) packet;
    for (int i = 0; i < 6; i++) { eth->dst[i] = 0xFF; eth->src[i] = net_mac()[i]; }
    eth->ethertype = htons(ETHERTYPE_IPV4);

    // IPv4 header
    ipv4_header_t* ip = (ipv4_header_t*)(packet + sizeof(eth_header_t));
    ip->ver_ihl   = 0x45;        // version 4, IHL 5
    ip->total_len = htons(sizeof(ipv4_header_t) + sizeof(icmp_header_t));
    ip->ttl       = 64;
    ip->protocol  = IP_PROTO_ICMP;
    for (int i = 0; i < 4; i++) { ip->src[i] = net_ip()[i]; ip->dst[i] = net_ip()[i]; }
    ip->checksum  = 0;
    ip->checksum  = htons(net_checksum(ip, sizeof(ipv4_header_t)));

    // ICMP header
    icmp_header_t* icmp = (icmp_header_t*)((uint8_t*)ip + sizeof(ipv4_header_t));
    icmp->type     = ICMP_ECHO_REQUEST;
    icmp->code     = 0;
    icmp->id       = htons(1);
    icmp->seq      = htons(1);
    icmp->checksum = 0;
    icmp->checksum = htons(net_checksum(icmp, sizeof(icmp_header_t)));

    print("  Ethernet : dst=ff:ff:ff:ff:ff:ff  type=IPv4\n");
    print("  IPv4     : src=");
    for (int i=0;i<4;i++){ print_int(ip->src[i]); if(i<3) print_char('.'); }
    print(" proto=ICMP  csum=");
    print_hex(ntohs(ip->checksum));
    print_char('\n');
    print("  ICMP     : type=8 (echo request)  csum=");
    print_hex(ntohs(icmp->checksum));
    print_char('\n');

    // Verify: recomputing checksum over header+checksum should yield 0
    uint16_t verify = net_checksum(ip, sizeof(ipv4_header_t));
    print("\n  IPv4 checksum verify: ");
    if (verify == 0)
        print_color("VALID (0x0000)\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    else
        print_color("INVALID\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));

    print_color("\n  Packet built & validated through the stack.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_exec() {
    print_color("\n  Loading ELF64 binary 'init'...\n", YELLOW_ON_BLACK);

    uint64_t entry = elf_load(user_init_elf, user_init_elf_len);
    if (!entry) {
        print_color("  exec: not a valid ELF64 binary\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("  Entry point: ");
    print_hex(entry);
    print("\n\n");

    // Run the loaded program in ring 3
    uint64_t stack_top = (uint64_t)(user_stack + sizeof(user_stack));
    enter_user_mode(entry, stack_top);

    print_color("\n  Program exited. Back in kernel.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_usermode() {
    print_color("\n  Dropping to Ring 3 (user mode)...\n\n", YELLOW_ON_BLACK);

    uint64_t stack_top = (uint64_t)(user_stack + sizeof(user_stack));
    enter_user_mode((uint64_t)user_program, stack_top);

    print_color("\n  Returned to Ring 0 (kernel) safely.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_syscall() {
    print_color("\n  Invoking system calls via int 0x80:\n\n", YELLOW_ON_BLACK);

    // SYS_WRITE
    print("  SYS_WRITE  -> ");
    uint64_t n = do_syscall(SYS_WRITE, (uint64_t)"Hello from a syscall!");
    print("  ("); print_int(n); print(" bytes)\n");

    // SYS_GETPID
    print("  SYS_GETPID -> pid ");
    print_int(do_syscall(SYS_GETPID, 0));
    print_char('\n');

    // SYS_UPTIME
    print("  SYS_UPTIME -> ");
    print_int(do_syscall(SYS_UPTIME, 0));
    print(" ms\n");

    // SYS_VERSION
    print("  SYS_VERSION-> phase ");
    print_int(do_syscall(SYS_VERSION, 0));
    print_char('\n');

    print_color("\n  All syscalls returned via rax.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_sysinfo() {
    rtc_time_t t;
    rtc_read(&t);

    print_color("\n  ===== VYRO OS SYSTEM INFO =====\n", CYAN_ON_BLACK);
    print("  OS        : Vyro OS v0.11.0\n");
    print("  Arch      : x86_64 (64-bit long mode)\n");
    print("  Kernel    : custom monolithic\n");
    print("  Display   : 1024x768 VESA framebuffer\n");

    print("  Uptime    : ");
    print_int(timer_uptime_seconds()); print(" s\n");

    print("  Time      : ");
    print_int(t.hour); print(":"); print_int(t.minute);
    print(":"); print_int(t.second); print(" UTC\n");

    print("  Phys mem  : ");
    print_int(pmm_free_pages() * 4); print(" KB free / ");
    print_int(pmm_total_pages() * 4); print(" KB\n");

    print("  Heap      : ");
    print_int(heap_used()); print(" bytes used\n");

    print_color("  ===============================\n\n", CYAN_ON_BLACK);
}

static void cmd_reboot() {
    print_color("\n  Rebooting Vyro OS...\n", YELLOW_ON_BLACK);
    sleep_ms(400);
    power_reboot();
}

static void cmd_shutdown() {
    print_color("\n  Shutting down Vyro OS. Goodbye.\n", YELLOW_ON_BLACK);
    sleep_ms(500);
    power_shutdown();
}

static void cmd_not_found(const char* cmd) {
    print_color("\n  vyro: command not found: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    print(cmd);
    print_color("\n  Type 'help' for available commands.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// Command dispatch table
// ─────────────────────────────────────────────────
typedef struct {
    const char* name;
    void (*handler)();
} command_t;

static const command_t commands[] = {
    { "help",    cmd_help    },
    { "clear",   cmd_clear   },
    { "cls",     cmd_clear   },
    { "echo",    cmd_echo    },
    { "version", cmd_version },
    { "ver",     cmd_version },
    { "about",   cmd_about   },
    { "history", cmd_history },
    { "color",   cmd_color   },
    { "mem",     cmd_mem     },
    { "sysinfo", cmd_sysinfo },
    { "tasks",   cmd_tasks   },
    { "ps",      cmd_ps      },
    { "syscall", cmd_syscall },
    { "usermode",cmd_usermode},
    { "exec",    cmd_exec    },
    { "pci",       cmd_pci     },
    { "net",       cmd_net     },
    { "ping",      cmd_ping    },
    { "realping",  cmd_realping},
    { "dhcp",      cmd_dhcp    },
    { "nslookup",  cmd_nslookup},
    { "udp",       cmd_udp     },
    { "tcp",       cmd_tcp     },
    { "tcpconnect",cmd_tcpconnect},
    { "tcplisten", cmd_tcplisten },
    { "tcpaccept", cmd_tcpaccept },
    { "tcpsend",   cmd_tcpsend   },
    { "tcprecv",   cmd_tcprecv   },
    { "crypto",    cmd_crypto    },
    { "x509",      cmd_x509      },
    { "tlskdf",    cmd_tlskdf    },
    { "disk",      cmd_disk    },
    { "diskwrite", cmd_diskwrite },
    { "diskread",  cmd_diskread  },
    { "usb",       cmd_usb     },
    { "beep",      cmd_beep    },
    { "play",      cmd_play    },
    { "gui",       cmd_gui     },
    { "whoami",    cmd_whoami  },
    { "login",     cmd_login   },
    { "logout",    cmd_logout  },
    { "useradd",   cmd_useradd },
    { "users",     cmd_users   },
    { "sha256",    cmd_sha256  },
    { "vyropkg",   cmd_vyropkg },
    { "cpuinfo",   cmd_cpuinfo },
    { "dmesg",     cmd_dmesg   },
    { "peek",      cmd_peek    },
    { "prof",      cmd_prof    },
    { "browser",   cmd_browser },
    { "uptime",  cmd_uptime  },
    { "date",    cmd_date    },
    { "time",    cmd_time    },
    { "sleep",   cmd_sleep   },
    { "ls",      cmd_ls      },
    { "pwd",     cmd_pwd     },
    { "cd",      cmd_cd      },
    { "mkdir",   cmd_mkdir   },
    { "touch",   cmd_touch   },
    { "write",   cmd_write   },
    { "cat",     cmd_cat     },
    { "rm",      cmd_rm      },
    { "tree",    cmd_tree    },
    { "reboot",   cmd_reboot   },
    { "shutdown", cmd_shutdown },
    { "poweroff", cmd_shutdown },
};

#define NUM_COMMANDS (sizeof(commands) / sizeof(commands[0]))

static void dispatch(const char* input) {
    if (input[0] == '\0') return;

    parse_args(input);
    if (argc == 0) return;

    for (uint32_t i = 0; i < NUM_COMMANDS; i++) {
        if (kstrcmp(argv[0], commands[i].name) == 0) {
            commands[i].handler();
            return;
        }
    }
    cmd_not_found(argv[0]);
}

// ─────────────────────────────────────────────────
// Print the shell prompt
// ─────────────────────────────────────────────────
static void print_prompt() {
    fs_ensure();
    char path[256];
    vfs_full_path(cwd, path, sizeof(path));
    print_color(current_user(), MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_color("@vyro", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_color(":", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_color(path, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
    print_color("> ", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// shell_init: print welcome message
// ─────────────────────────────────────────────────
void shell_init() {
    print_color("  Type 'help' for commands. Use UP/DOWN for history.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_prompt();
}

// ─────────────────────────────────────────────────
// shell_run: main shell loop (never returns)
// ─────────────────────────────────────────────────
void shell_run() {
    static char input[MAX_INPUT];
    static int  input_len = 0;
    static int  hist_nav  = -1;

    while (1) {
        __asm__ volatile("hlt");

        while (keyboard_has_input()) {
            char c = keyboard_getchar();

            // ── Arrow keys ──
            if (c == KEY_UP) {
                if (history_count == 0) continue;
                if (hist_nav == -1)
                    hist_nav = history_count - 1;
                else if (hist_nav > 0)
                    hist_nav--;

                // Clear current line
                for (int i = 0; i < input_len; i++) {
                    print_char('\b');
                }
                kstrcpy(input, history[hist_nav % HISTORY_SIZE]);
                input_len = kstrlen(input);
                print(input);
                continue;
            }

            if (c == KEY_DOWN) {
                if (hist_nav == -1) continue;
                hist_nav++;
                for (int i = 0; i < input_len; i++) {
                    print_char('\b');
                }
                if (hist_nav >= history_count) {
                    hist_nav = -1;
                    input[0] = '\0';
                    input_len = 0;
                } else {
                    kstrcpy(input, history[hist_nav % HISTORY_SIZE]);
                    input_len = kstrlen(input);
                    print(input);
                }
                continue;
            }

            // ── Backspace ──
            if (c == KEY_BACKSPACE) {
                if (input_len > 0) {
                    input_len--;
                    print_char('\b');
                    print_char(' ');
                    print_char('\b');
                }
                continue;
            }

            // ── Enter ──
            if (c == '\n') {
                print_char('\n');
                input[input_len] = '\0';
                history_push(input);
                hist_nav  = -1;
                dispatch(input);
                input_len = 0;
                input[0]  = '\0';
                print_prompt();
                continue;
            }

            // ── Printable character ──
            if (c >= ' ' && c < 127 && input_len < MAX_INPUT - 1) {
                input[input_len++] = c;
                print_char(c);
            }
        }
    }
}
