#include "shell.h"
#include "pmm.h"
#include "heap.h"
#include "../drivers/screen.h"
#include "../drivers/keyboard.h"
#include "../drivers/timer.h"
#include "../drivers/rtc.h"
#include "vfs.h"
#include "task.h"
#include "syscall.h"
#include "elf.h"
#include "pci.h"
#include "net.h"
#include "ata.h"
#include "usb.h"
#include "../drivers/speaker.h"
#include "gui.h"
#include "security.h"
#include "sha256.h"
#include "pkg.h"
#include "smp.h"
#include "../include/types.h"

// Embedded user ELF binary (generated by Makefile into build/user_init.c)
extern const unsigned char user_init_elf[];
extern const unsigned int  user_init_elf_len;

// ─────────────────────────────────────────────────
// Userland-style syscall wrappers — invoke int 0x80
// (exactly how a user program would call the kernel)
// ─────────────────────────────────────────────────
static uint64_t do_syscall(uint64_t num, uint64_t arg1) {
    uint64_t ret;
    __asm__ volatile("int $0x80"
                     : "=a"(ret)
                     : "a"(num), "D"(arg1)
                     : "memory");
    return ret;
}

// ─────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────
#define MAX_INPUT      256
#define MAX_ARGS       16
#define HISTORY_SIZE   10

// Arrow key special values (set by keyboard driver)
#define KEY_UP    0x01
#define KEY_DOWN  0x02
#define KEY_LEFT  0x03
#define KEY_RIGHT 0x04

// ─────────────────────────────────────────────────
// String utilities (no stdlib in freestanding env)
// ─────────────────────────────────────────────────
static int kstrlen(const char* s) {
    int i = 0;
    while (s[i]) i++;
    return i;
}

static int kstrcmp(const char* a, const char* b) {
    while (*a && *b && *a == *b) { a++; b++; }
    return *a - *b;
}

static void kstrcpy(char* dst, const char* src) {
    while ((*dst++ = *src++));
}

// ─────────────────────────────────────────────────
// Command history ring buffer
// ─────────────────────────────────────────────────
static char    history[HISTORY_SIZE][MAX_INPUT];
static int     history_count   = 0;

static void history_push(const char* cmd) {
    if (cmd[0] == '\0') return;
    // Don't duplicate last entry
    if (history_count > 0) {
        int last = (history_count - 1) % HISTORY_SIZE;
        if (kstrcmp(history[last], cmd) == 0) return;
    }
    kstrcpy(history[history_count % HISTORY_SIZE], cmd);
    history_count++;
}

// ─────────────────────────────────────────────────
// Argument parser — splits input into argv tokens
// "echo hello world" → argv[0]="echo" argv[1]="hello" argv[2]="world"
// ─────────────────────────────────────────────────
static char* argv[MAX_ARGS];
static int   argc;
static char  parse_buf[MAX_INPUT];

static void parse_args(const char* input) {
    argc = 0;
    kstrcpy(parse_buf, input);
    char* p = parse_buf;

    while (*p && argc < MAX_ARGS) {
        // Skip spaces
        while (*p == ' ') p++;
        if (*p == '\0') break;

        argv[argc++] = p;

        // Find end of token
        while (*p && *p != ' ') p++;
        if (*p == ' ') *p++ = '\0';
    }
}

// ─────────────────────────────────────────────────
// Built-in commands
// ─────────────────────────────────────────────────
static void cmd_help() {
    print_color("\n  Vyro OS Shell Commands\n", YELLOW_ON_BLACK);
    print_color("  ─────────────────────────────────────\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    print_color("  help     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show this help menu\n");
    print_color("  clear    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Clear the screen\n");
    print_color("  echo     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Print text to screen\n");
    print_color("  version  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show OS version info\n");
    print_color("  about    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("About Vyro OS\n");
    print_color("  color    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Change terminal color (0-15)\n");
    print_color("  history  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show command history\n");
    print_color("  mem      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show memory usage\n");
    print_color("  sysinfo  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Full system dashboard\n");
    print_color("  tasks    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Run multitasking demo\n");
    print_color("  ps       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List processes\n");
    print_color("  syscall  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Demo system calls (int 0x80)\n");
    print_color("  usermode ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Drop to ring 3 and back\n");
    print_color("  exec     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Load & run an ELF64 binary\n");
    print_color("  pci      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List PCI devices\n");
    print_color("  net      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show network config\n");
    print_color("  ping     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Build & validate ICMP packet\n");
    print_color("  disk     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show ATA disk info\n");
    print_color("  diskwrite", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print(" Write text to a sector\n");
    print_color("  diskread ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Read a sector\n");
    print_color("  usb      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show USB controller info\n");
    print_color("  beep     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Beep <freq> <ms>\n");
    print_color("  play     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Play a musical scale\n");
    print_color("  gui      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Launch graphical desktop\n");
    print_color("  whoami   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current user\n");
    print_color("  login    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("login <user> <pass>\n");
    print_color("  logout   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Log out to guest\n");
    print_color("  useradd  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Add user (admin only)\n");
    print_color("  users    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List user accounts\n");
    print_color("  sha256   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Hash text with SHA-256\n");
    print_color("  vyropkg  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Package manager\n");
    print_color("  cpuinfo  ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show CPU cores (ACPI)\n");
    print_color("  uptime   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show system uptime\n");
    print_color("  date     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current date & time\n");
    print_color("  time     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show current time\n");
    print_color("  ls       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("List directory contents\n");
    print_color("  pwd      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Print working directory\n");
    print_color("  cd       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Change directory\n");
    print_color("  mkdir    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Create directory\n");
    print_color("  touch    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Create empty file\n");
    print_color("  write    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Write text to a file\n");
    print_color("  cat      ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show file contents\n");
    print_color("  rm       ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Remove file or directory\n");
    print_color("  tree     ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Show filesystem tree\n");
    print_color("  sleep    ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Sleep N milliseconds\n");
    print_color("  reboot   ", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
    print("Reboot the system\n");
    print_color("  ─────────────────────────────────────\n\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
}

static void cmd_clear() {
    screen_clear(WHITE_ON_BLACK);
    // Reprint minimal header after clear
    print_color("  Vyro OS v0.6.0  |  64-bit  |  x86_64\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

static void cmd_echo() {
    print_char('\n');
    for (int i = 1; i < argc; i++) {
        print(argv[i]);
        if (i < argc - 1) print_char(' ');
    }
    print("\n\n");
}

static void cmd_version() {
    print_color("\n  Vyro OS\n", CYAN_ON_BLACK);
    print("  Version   : 0.6.0\n");
    print("  Phase     : 6 (Interactive Shell)\n");
    print("  Arch      : x86_64 (64-bit)\n");
    print("  Kernel    : Custom (no Linux)\n");
    print("  Language  : NASM Assembly + C\n");
    print("  License   : MIT\n");
    print("  Budget    : $0\n\n");
}

static void cmd_about() {
    print_color("\n  About Vyro OS\n", CYAN_ON_BLACK);
    print("  Built from scratch — no Linux, no BSD, no shortcuts.\n");
    print("  Every line of code written by hand.\n");
    print("  Bootloader -> Protected Mode -> Long Mode -> Kernel -> Shell\n\n");
}

static void cmd_history() {
    print_char('\n');
    if (history_count == 0) {
        print_color("  No history yet.\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
        return;
    }
    int start = history_count > HISTORY_SIZE ? history_count - HISTORY_SIZE : 0;
    int n = 1;
    for (int i = start; i < history_count; i++) {
        print_color("  ", WHITE_ON_BLACK);
        print_int(n++);
        print("  ");
        print(history[i % HISTORY_SIZE]);
        print_char('\n');
    }
    print_char('\n');
}

static void cmd_color() {
    if (argc < 2) {
        print_color("\n  Usage: color <0-15>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Parse number from argv[1]
    int n = 0;
    const char* p = argv[1];
    while (*p >= '0' && *p <= '9') n = n * 10 + (*p++ - '0');
    if (n < 0 || n > 15) {
        print_color("\n  Color must be 0-15\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    screen_set_color(MAKE_COLOR(n, COLOR_BLACK));
    print("\n  Color changed.\n\n");
    screen_set_color(WHITE_ON_BLACK);
}

static void cmd_mem() {
    uint32_t total_pages = pmm_total_pages();
    uint32_t used_pages  = pmm_used_pages();
    uint32_t free_pages  = pmm_free_pages();
    uint64_t heap_u      = heap_used();
    uint64_t heap_t      = heap_total();

    print_color("\n  Physical Memory\n", YELLOW_ON_BLACK);
    print("  Total pages : "); print_int(total_pages);
    print(" ("); print_int(total_pages * 4); print(" KB)\n");
    print("  Used pages  : "); print_int(used_pages);
    print(" ("); print_int(used_pages * 4); print(" KB)\n");
    print("  Free pages  : "); print_int(free_pages);
    print(" ("); print_int(free_pages * 4); print(" KB)\n");

    print_color("\n  Heap Memory\n", YELLOW_ON_BLACK);
    print("  Total : "); print_int(heap_t / 1024); print(" KB\n");
    print("  Used  : "); print_int(heap_u); print(" bytes\n");
    print("  Free  : "); print_int((heap_t - heap_u) / 1024); print(" KB\n");

    print_color("\n  Memory Map\n", YELLOW_ON_BLACK);
    print("  0x000000 - 0x00FFFF  Bootloader + page tables\n");
    print("  0x010000 - 0x017FFF  Kernel binary\n");
    print("  0x100000 - 0x1FFFFF  PMM bitmap\n");
    print("  0x200000 - 0x4FFFFF  PMM managed pages\n");
    print("  0x500000 - 0xCFFFFF  Heap (8MB)\n\n");
}

// Print a 2-digit zero-padded number
static void print_2d(uint8_t n) {
    print_char('0' + (n / 10));
    print_char('0' + (n % 10));
}

static const char* month_names[] = {
    "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
};

static void cmd_time() {
    rtc_time_t t;
    rtc_read(&t);
    print("\n  ");
    print_2d(t.hour);   print_char(':');
    print_2d(t.minute); print_char(':');
    print_2d(t.second);
    print(" (UTC)\n\n");
}

static void cmd_date() {
    rtc_time_t t;
    rtc_read(&t);
    print("\n  ");
    if (t.month >= 1 && t.month <= 12) print(month_names[t.month]);
    print_char(' ');
    print_int(t.day);
    print(", ");
    print_int(t.year);
    print("  ");
    print_2d(t.hour);   print_char(':');
    print_2d(t.minute); print_char(':');
    print_2d(t.second);
    print(" UTC\n\n");
}

static void cmd_uptime() {
    uint64_t secs  = timer_uptime_seconds();
    uint64_t ms    = timer_uptime_ms();
    uint64_t ticks = timer_ticks();

    uint64_t hours = secs / 3600;
    uint64_t mins  = (secs % 3600) / 60;
    uint64_t s     = secs % 60;

    print_color("\n  System Uptime\n", YELLOW_ON_BLACK);
    print("  ");
    print_int(hours); print("h ");
    print_int(mins);  print("m ");
    print_int(s);     print("s\n");
    print("  Total : "); print_int(ms);    print(" ms\n");
    print("  Ticks : "); print_int(ticks); print(" (@100 Hz)\n\n");
}

static void cmd_sleep() {
    if (argc < 2) {
        print_color("\n  Usage: sleep <milliseconds>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t ms = 0;
    const char* p = argv[1];
    while (*p >= '0' && *p <= '9') ms = ms * 10 + (*p++ - '0');

    print("\n  Sleeping for ");
    print_int(ms);
    print(" ms...");
    sleep_ms(ms);
    print_color(" done.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// Filesystem commands — track current working directory
// ─────────────────────────────────────────────────
static vfs_node_t* cwd = 0;

static void fs_ensure() {
    if (!cwd) cwd = vfs_root();
}

static void cmd_pwd() {
    fs_ensure();
    char path[256];
    vfs_full_path(cwd, path, sizeof(path));
    print("\n  ");
    print(path);
    print("\n\n");
}

static void cmd_ls() {
    fs_ensure();
    vfs_node_t* dir = cwd;

    // Optional argument: ls <dir>
    if (argc >= 2) {
        vfs_node_t* target = vfs_find(cwd, argv[1]);
        if (!target) {
            print_color("\n  ls: no such directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            print(argv[1]); print("\n\n");
            return;
        }
        dir = target;
    }

    print_char('\n');
    vfs_node_t* cur = dir->first_child;
    if (!cur) {
        print_color("  (empty)\n\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        return;
    }
    while (cur) {
        if (cur->type == VFS_DIRECTORY) {
            print_color("  ", WHITE_ON_BLACK);
            print_color(cur->name, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            print_color("/\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
        } else {
            print("  ");
            print(cur->name);
            print("  (");
            print_int(cur->size);
            print(" bytes)\n");
        }
        cur = cur->next_sibling;
    }
    print_char('\n');
}

static void cmd_cd() {
    fs_ensure();
    if (argc < 2) { cwd = vfs_root(); return; }

    vfs_node_t* target = vfs_find(cwd, argv[1]);
    if (!target) {
        print_color("\n  cd: no such directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    if (target->type != VFS_DIRECTORY) {
        print_color("\n  cd: not a directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    cwd = target;
}

static void cmd_mkdir() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: mkdir <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_create(cwd, argv[1], VFS_DIRECTORY)) {
        print_color("\n  mkdir: cannot create '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("' (exists?)\n\n");
    }
}

static void cmd_touch() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: touch <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_create(cwd, argv[1], VFS_FILE)) {
        print_color("\n  touch: cannot create '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("' (exists?)\n\n");
    }
}

static void cmd_write() {
    fs_ensure();
    if (argc < 3) {
        print_color("\n  Usage: write <file> <text...>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    vfs_node_t* file = vfs_find(cwd, argv[1]);
    if (!file) {
        // Auto-create the file
        file = vfs_create(cwd, argv[1], VFS_FILE);
        if (!file) {
            print_color("\n  write: cannot create file\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            return;
        }
    }
    if (file->type != VFS_FILE) {
        print_color("\n  write: not a file\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    // Join argv[2..] into one string buffer
    static char buf[1024];
    int pos = 0;
    for (int i = 2; i < argc && pos < 1020; i++) {
        const char* w = argv[i];
        for (int j = 0; w[j] && pos < 1020; j++) buf[pos++] = w[j];
        if (i < argc - 1 && pos < 1020) buf[pos++] = ' ';
    }
    buf[pos] = '\0';

    vfs_write(file, buf);
}

static void cmd_cat() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: cat <file>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    vfs_node_t* file = vfs_find(cwd, argv[1]);
    if (!file) {
        print_color("\n  cat: no such file: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
        return;
    }
    if (file->type != VFS_FILE) {
        print_color("\n  cat: is a directory\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    print("\n  ");
    print(vfs_read(file));
    print("\n\n");
}

static void cmd_rm() {
    fs_ensure();
    if (argc < 2) {
        print_color("\n  Usage: rm <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (!vfs_remove(cwd, argv[1])) {
        print_color("\n  rm: no such file or directory: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        print(argv[1]); print("\n\n");
    }
}

// Recursive tree printer
static void tree_print(vfs_node_t* node, int depth) {
    vfs_node_t* cur = node->first_child;
    while (cur) {
        for (int i = 0; i < depth; i++) print("  ");
        print("  ");
        if (cur->type == VFS_DIRECTORY) {
            print_color(cur->name, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            print_color("/\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
            tree_print(cur, depth + 1);
        } else {
            print(cur->name);
            print_char('\n');
        }
        cur = cur->next_sibling;
    }
}

static void cmd_tree() {
    fs_ensure();
    print_color("\n  /\n", MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
    tree_print(vfs_root(), 0);
    print_char('\n');
}

// ─────────────────────────────────────────────────
// Multitasking demo tasks
// Each prints its label a few times, yielding between,
// so you can see the round-robin interleaving.
// ─────────────────────────────────────────────────
static void demo_task_a() {
    for (int i = 0; i < 5; i++) {
        print_color("[A]", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void demo_task_b() {
    for (int i = 0; i < 5; i++) {
        print_color("[B]", MAKE_COLOR(COLOR_LIGHT_CYAN, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void demo_task_c() {
    for (int i = 0; i < 5; i++) {
        print_color("[C]", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
        task_yield();
    }
    task_exit();
}

static void cmd_tasks() {
    print_color("\n  Spawning 3 cooperative tasks...\n  Output: ", WHITE_ON_BLACK);

    tasking_init();
    task_create("task-a", demo_task_a);
    task_create("task-b", demo_task_b);
    task_create("task-c", demo_task_c);

    // Run scheduler — returns when all tasks finish
    task_run_all();

    print_color("\n  All tasks finished.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_ps() {
    print_color("\n  PID  NAME            STATE\n", YELLOW_ON_BLACK);
    print_color("  ---  --------------  --------\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    print("  1    kernel/shell    RUNNING\n");

    uint32_t n = task_count();
    if (n == 0) {
        print_color("  (no background tasks)\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    }
    print_char('\n');
}

// ─────────────────────────────────────────────────
// Ring-3 user program. Runs UNPRIVILEGED. Its only way
// to talk to the kernel is int 0x80. No direct hardware,
// no privileged instructions allowed.
// ─────────────────────────────────────────────────
extern void enter_user_mode(uint64_t entry, uint64_t user_stack);
static uint8_t user_stack[8192] __attribute__((aligned(16)));

static void user_program() {
    // SYS_WRITE — print a message from ring 3
    __asm__ volatile("int $0x80" : : "a"(SYS_WRITE),
                     "D"("  [ring3] Hello from user mode!\n") : "memory");

    // SYS_GETPID
    uint64_t pid;
    __asm__ volatile("int $0x80" : "=a"(pid) : "a"(SYS_GETPID), "D"(0));
    __asm__ volatile("int $0x80" : : "a"(SYS_WRITE),
                     "D"("  [ring3] Made syscalls without crashing.\n") : "memory");

    // SYS_EXIT — return to the kernel (does not come back)
    __asm__ volatile("int $0x80" : : "a"(SYS_EXIT), "D"(0));

    // Should never reach here
    for (;;) {}
}

// Print a hex byte (2 digits)
static void print_hex2(uint8_t b) {
    const char* h = "0123456789ABCDEF";
    print_char(h[b >> 4]);
    print_char(h[b & 0xF]);
}

static uint32_t parse_uint(const char* p) {
    uint32_t n = 0;
    while (*p >= '0' && *p <= '9') n = n * 10 + (*p++ - '0');
    return n;
}

static void cmd_disk() {
    print_color("\n  ATA Disk (primary slave)\n", YELLOW_ON_BLACK);
    if (ata_init()) {
        print_color("  Status : present, ATA, LBA28\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print("  Sector : 512 bytes\n");
        print("  Use 'diskwrite <lba> <text>' and 'diskread <lba>'\n\n");
    } else {
        print_color("  Status : no disk detected\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_diskwrite() {
    if (argc < 3) {
        print_color("\n  Usage: diskwrite <lba> <text>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t lba = parse_uint(argv[1]);

    static uint8_t sector[512];
    for (int i = 0; i < 512; i++) sector[i] = 0;

    // Join argv[2..] into the sector buffer
    int pos = 0;
    for (int i = 2; i < argc && pos < 510; i++) {
        const char* w = argv[i];
        for (int j = 0; w[j] && pos < 510; j++) sector[pos++] = (uint8_t)w[j];
        if (i < argc - 1 && pos < 510) sector[pos++] = ' ';
    }

    if (ata_write_sector(lba, sector) == 0) {
        print("\n  Wrote ");
        print_int(pos);
        print(" bytes to LBA ");
        print_int(lba);
        print_color("  [persisted to disk]\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    } else {
        print_color("\n  diskwrite: write failed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_diskread() {
    if (argc < 2) {
        print_color("\n  Usage: diskread <lba>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    uint32_t lba = parse_uint(argv[1]);

    static uint8_t sector[512];
    if (ata_read_sector(lba, sector) != 0) {
        print_color("\n  diskread: read failed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("\n  LBA ");
    print_int(lba);
    print(" contents: \"");
    // Print as text up to first NUL
    for (int i = 0; i < 512 && sector[i]; i++) print_char((char)sector[i]);
    print("\"\n\n");
}

static void cmd_cpuinfo() {
    print_color("\n  CPU Information (via ACPI MADT)\n", YELLOW_ON_BLACK);

    print("  ACPI       : ");
    if (acpi_found()) print_color("found\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    else print_color("not found\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));

    print("  CPU cores  : ");
    print_int(cpu_count());
    print_char('\n');

    print("  LAPIC addr : ");
    print_hex(lapic_address());
    print_char('\n');

    print("  APIC IDs   : ");
    for (uint32_t i = 0; i < cpu_count(); i++) {
        print_int(cpu_apic_id(i));
        if (i < cpu_count() - 1) print(", ");
    }
    print("\n\n");
}

static void cmd_vyropkg() {
    if (argc < 2) {
        print_color("\n  vyropkg - Vyro OS package manager\n", YELLOW_ON_BLACK);
        print("  Usage:\n");
        print("    vyropkg list             list available packages\n");
        print("    vyropkg installed        list installed packages\n");
        print("    vyropkg install <name>   install a package + deps\n");
        print("    vyropkg remove <name>    remove a package\n");
        print("    vyropkg search <name>    find a package\n\n");
        return;
    }

    if (kstrcmp(argv[1], "list") == 0) {
        int n; package_t* r = pkg_repo(&n);
        print_color("\n  Available packages\n", YELLOW_ON_BLACK);
        for (int i = 0; i < n; i++) {
            print(r[i].installed ? "  [x] " : "  [ ] ");
            print(r[i].name);
            print("  v"); print(r[i].version);
            print("  - "); print(r[i].desc);
            print_char('\n');
        }
        print_char('\n');

    } else if (kstrcmp(argv[1], "installed") == 0) {
        int n; package_t* r = pkg_repo(&n);
        print_color("\n  Installed packages\n", YELLOW_ON_BLACK);
        int any = 0;
        for (int i = 0; i < n; i++) {
            if (r[i].installed) {
                print("  "); print(r[i].name); print(" v"); print(r[i].version); print_char('\n');
                any = 1;
            }
        }
        if (!any) print_color("  (none installed)\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
        print_char('\n');

    } else if (kstrcmp(argv[1], "install") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg install <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        print_color("\n  Resolving dependencies for '", WHITE_ON_BLACK);
        print(argv[2]); print("'...\n");
        int r = pkg_install(argv[2]);
        if (r < 0) {
            print_color("  vyropkg: package not found\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        } else if (r == 0) {
            print_color("  already installed.\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
        } else {
            print_color("  Done. ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
            print_int(r); print(" package(s) installed (see /bin).\n\n");
        }

    } else if (kstrcmp(argv[1], "remove") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg remove <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        if (pkg_remove(argv[2]) == 0) {
            print_color("\n  Removed '", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
            print(argv[2]); print("'.\n\n");
        } else {
            print_color("\n  vyropkg: not installed\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        }

    } else if (kstrcmp(argv[1], "search") == 0) {
        if (argc < 3) { print_color("\n  Usage: vyropkg search <name>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK)); return; }
        package_t* p = pkg_find(argv[2]);
        if (p) {
            print("\n  "); print(p->name); print(" v"); print(p->version);
            print("\n  "); print(p->desc); print("\n\n");
        } else {
            print_color("\n  No package named '", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
            print(argv[2]); print("'\n\n");
        }
    } else {
        print_color("\n  vyropkg: unknown subcommand\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_whoami() {
    print("\n  ");
    print(current_user());
    if (current_is_admin()) print_color("  (admin)\n\n", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
    else print_color("  (standard user)\n\n", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

static void cmd_login() {
    if (argc < 3) {
        print_color("\n  Usage: login <user> <password>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    int r = auth_login(argv[1], argv[2]);
    if (r == 0) {
        print_color("\n  Login successful. Welcome, ", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print(current_user());
        print(".\n\n");
    } else if (r == -1) {
        print_color("\n  login: incorrect password\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    } else {
        print_color("\n  login: no such user\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_logout() {
    auth_logout();
    print_color("\n  Logged out. Now: ", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print(current_user());
    print("\n\n");
}

static void cmd_useradd() {
    if (!current_is_admin()) {
        print_color("\n  useradd: permission denied (admin only)\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (argc < 3) {
        print_color("\n  Usage: useradd <user> <password>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    if (user_add(argv[1], argv[2], 0) == 0) {
        print_color("\n  User '", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
        print(argv[1]); print("' created.\n\n");
    } else {
        print_color("\n  useradd: failed (exists or full)\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
}

static void cmd_users() {
    user_t* list;
    int n = user_list(&list);
    print_color("\n  USERS\n", YELLOW_ON_BLACK);
    print_color("  UID   NAME            ROLE\n", MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    for (int i = 0; i < n; i++) {
        print("  ");
        print_int(list[i].uid);
        print("  ");
        print(list[i].name);
        // pad
        int pad = 16 - (int)0; (void)pad;
        print("   ");
        if (list[i].is_admin) print_color("admin\n", MAKE_COLOR(COLOR_YELLOW, COLOR_BLACK));
        else print("user\n");
    }
    print_char('\n');
}

static void cmd_sha256() {
    if (argc < 2) {
        print_color("\n  Usage: sha256 <text>\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }
    // Hash argv[1] (single token)
    const char* s = argv[1];
    int len = 0; while (s[len]) len++;
    uint8_t digest[32];
    char hex[65];
    sha256((const uint8_t*)s, len, digest);
    sha256_hex(digest, hex);
    print("\n  sha256(\"");
    print(s);
    print("\") =\n  ");
    print_color(hex, MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print("\n\n");
}

static void cmd_gui() {
    print_color("\n  Launching GUI desktop... (ESC to return)\n", YELLOW_ON_BLACK);
    sleep_ms(300);
    gui_run();
    // Returning to text mode: clear and redraw a minimal header
    screen_clear(WHITE_ON_BLACK);
    print_color("  Exited GUI. Back to shell.\n\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_beep() {
    uint32_t freq = 440;   // default A4
    uint32_t dur  = 200;
    if (argc >= 2) freq = parse_uint(argv[1]);
    if (argc >= 3) dur  = parse_uint(argv[2]);

    print("\n  Beep: ");
    print_int(freq);
    print(" Hz for ");
    print_int(dur);
    print(" ms\n\n");

    beep(freq, dur);
}

static void cmd_play() {
    print_color("\n  Playing scale (C major)...\n\n", YELLOW_ON_BLACK);

    int notes[]    = { NOTE_C4, NOTE_D4, NOTE_E4, NOTE_F4,
                       NOTE_G4, NOTE_A4, NOTE_B4, NOTE_C5 };
    const char* nm[] = { "C", "D", "E", "F", "G", "A", "B", "C" };

    for (int i = 0; i < 8; i++) {
        print("  ");
        print(nm[i]);
        beep((uint32_t)notes[i], 200);
        sleep_ms(40);
    }
    print("\n\n");
}

static void cmd_usb() {
    print_color("\n  USB Subsystem\n", YELLOW_ON_BLACK);

    pci_device_t* c = pci_find_class(0x0C, 0x03);
    if (!c) {
        print_color("  No USB host controller found.\n\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("  Controller : ");
    print(usb_controller_type());
    print_char('\n');

    print("  PCI        : ");
    print_hex(c->vendor_id); print(":"); print_hex(c->device_id);
    print("  (bus "); print_int(c->bus); print(" slot "); print_int(c->slot); print(")\n");

    print("  prog-if    : ");
    print_hex(c->prog_if);
    print_char('\n');

    print("  IRQ        : ");
    print_int(c->irq_line);
    print_char('\n');

    print_color("\n  Descriptor sizes: device=18B  setup=8B\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_color("  Controller detected & identified via PCI.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_pci() {
    print_color("\n  PCI Devices\n", YELLOW_ON_BLACK);
    print_color("  BUS:SLOT  VENDOR:DEVICE  CLASS  DESC\n",
                MAKE_COLOR(COLOR_DARK_GREY, COLOR_BLACK));
    uint32_t n = pci_device_count();
    for (uint32_t i = 0; i < n; i++) {
        pci_device_t* d = pci_get_device(i);
        print("  ");
        print_hex2(d->bus); print(":"); print_hex2(d->slot);
        print("     ");
        print_hex((d->vendor_id)); print(":"); print_hex(d->device_id);
        print("  ");
        print_hex2(d->class_id);
        print("    ");
        if (d->class_id == 0x02)      print("Network controller");
        else if (d->class_id == 0x01) print("Storage controller");
        else if (d->class_id == 0x03) print("Display controller");
        else if (d->class_id == 0x06) print("Bridge");
        else                          print("Device");
        print_char('\n');
    }
    print_char('\n');
}

static void cmd_net() {
    print_color("\n  Vyro OS Network Configuration\n", YELLOW_ON_BLACK);

    const uint8_t* mac = net_mac();
    print("  MAC : ");
    for (int i = 0; i < 6; i++) {
        print_hex2(mac[i]);
        if (i < 5) print_char(':');
    }
    print_char('\n');

    const uint8_t* ip = net_ip();
    print("  IP  : ");
    for (int i = 0; i < 4; i++) {
        print_int(ip[i]);
        if (i < 3) print_char('.');
    }
    print_char('\n');

    pci_device_t* nic = pci_find_network();
    print("  NIC : ");
    if (nic) {
        print_hex(nic->vendor_id); print(":"); print_hex(nic->device_id);
        print(" (IRQ "); print_int(nic->irq_line); print(")\n");
    } else {
        print_color("none detected\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    }
    print_char('\n');
}

// Build an ICMP echo request, run it through the stack (loopback),
// verify the checksum — demonstrates the protocol layers working.
static void cmd_ping() {
    print_color("\n  Building ICMP echo packet (loopback)...\n\n", YELLOW_ON_BLACK);

    static uint8_t packet[64];
    for (int i = 0; i < 64; i++) packet[i] = 0;

    // Ethernet header
    eth_header_t* eth = (eth_header_t*) packet;
    for (int i = 0; i < 6; i++) { eth->dst[i] = 0xFF; eth->src[i] = net_mac()[i]; }
    eth->ethertype = htons(ETHERTYPE_IPV4);

    // IPv4 header
    ipv4_header_t* ip = (ipv4_header_t*)(packet + sizeof(eth_header_t));
    ip->ver_ihl   = 0x45;        // version 4, IHL 5
    ip->total_len = htons(sizeof(ipv4_header_t) + sizeof(icmp_header_t));
    ip->ttl       = 64;
    ip->protocol  = IP_PROTO_ICMP;
    for (int i = 0; i < 4; i++) { ip->src[i] = net_ip()[i]; ip->dst[i] = net_ip()[i]; }
    ip->checksum  = 0;
    ip->checksum  = htons(net_checksum(ip, sizeof(ipv4_header_t)));

    // ICMP header
    icmp_header_t* icmp = (icmp_header_t*)((uint8_t*)ip + sizeof(ipv4_header_t));
    icmp->type     = ICMP_ECHO_REQUEST;
    icmp->code     = 0;
    icmp->id       = htons(1);
    icmp->seq      = htons(1);
    icmp->checksum = 0;
    icmp->checksum = htons(net_checksum(icmp, sizeof(icmp_header_t)));

    print("  Ethernet : dst=ff:ff:ff:ff:ff:ff  type=IPv4\n");
    print("  IPv4     : src=");
    for (int i=0;i<4;i++){ print_int(ip->src[i]); if(i<3) print_char('.'); }
    print(" proto=ICMP  csum=");
    print_hex(ntohs(ip->checksum));
    print_char('\n');
    print("  ICMP     : type=8 (echo request)  csum=");
    print_hex(ntohs(icmp->checksum));
    print_char('\n');

    // Verify: recomputing checksum over header+checksum should yield 0
    uint16_t verify = net_checksum(ip, sizeof(ipv4_header_t));
    print("\n  IPv4 checksum verify: ");
    if (verify == 0)
        print_color("VALID (0x0000)\n", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    else
        print_color("INVALID\n", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));

    print_color("\n  Packet built & validated through the stack.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_exec() {
    print_color("\n  Loading ELF64 binary 'init'...\n", YELLOW_ON_BLACK);

    uint64_t entry = elf_load(user_init_elf, user_init_elf_len);
    if (!entry) {
        print_color("  exec: not a valid ELF64 binary\n\n",
                    MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
        return;
    }

    print("  Entry point: ");
    print_hex(entry);
    print("\n\n");

    // Run the loaded program in ring 3
    uint64_t stack_top = (uint64_t)(user_stack + sizeof(user_stack));
    enter_user_mode(entry, stack_top);

    print_color("\n  Program exited. Back in kernel.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_usermode() {
    print_color("\n  Dropping to Ring 3 (user mode)...\n\n", YELLOW_ON_BLACK);

    uint64_t stack_top = (uint64_t)(user_stack + sizeof(user_stack));
    enter_user_mode((uint64_t)user_program, stack_top);

    print_color("\n  Returned to Ring 0 (kernel) safely.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_syscall() {
    print_color("\n  Invoking system calls via int 0x80:\n\n", YELLOW_ON_BLACK);

    // SYS_WRITE
    print("  SYS_WRITE  -> ");
    uint64_t n = do_syscall(SYS_WRITE, (uint64_t)"Hello from a syscall!");
    print("  ("); print_int(n); print(" bytes)\n");

    // SYS_GETPID
    print("  SYS_GETPID -> pid ");
    print_int(do_syscall(SYS_GETPID, 0));
    print_char('\n');

    // SYS_UPTIME
    print("  SYS_UPTIME -> ");
    print_int(do_syscall(SYS_UPTIME, 0));
    print(" ms\n");

    // SYS_VERSION
    print("  SYS_VERSION-> phase ");
    print_int(do_syscall(SYS_VERSION, 0));
    print_char('\n');

    print_color("\n  All syscalls returned via rax.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
}

static void cmd_sysinfo() {
    rtc_time_t t;
    rtc_read(&t);

    print_color("\n  ===== VYRO OS SYSTEM INFO =====\n", CYAN_ON_BLACK);
    print("  OS        : Vyro OS v0.11.0\n");
    print("  Arch      : x86_64 (64-bit long mode)\n");
    print("  Kernel    : custom monolithic\n");
    print("  Display   : 1024x768 VESA framebuffer\n");

    print("  Uptime    : ");
    print_int(timer_uptime_seconds()); print(" s\n");

    print("  Time      : ");
    print_int(t.hour); print(":"); print_int(t.minute);
    print(":"); print_int(t.second); print(" UTC\n");

    print("  Phys mem  : ");
    print_int(pmm_free_pages() * 4); print(" KB free / ");
    print_int(pmm_total_pages() * 4); print(" KB\n");

    print("  Heap      : ");
    print_int(heap_used()); print(" bytes used\n");

    print_color("  ===============================\n\n", CYAN_ON_BLACK);
}

static void cmd_reboot() {
    print_color("\n  Rebooting Vyro OS...\n", YELLOW_ON_BLACK);
    // Triple fault reboot — write bad IDT and trigger interrupt
    uint8_t bad[6] = {0};
    __asm__ volatile("lidt %0" : : "m"(bad));
    __asm__ volatile("int $0x00");
}

static void cmd_not_found(const char* cmd) {
    print_color("\n  vyro: command not found: ", MAKE_COLOR(COLOR_LIGHT_RED, COLOR_BLACK));
    print(cmd);
    print_color("\n  Type 'help' for available commands.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// Command dispatch table
// ─────────────────────────────────────────────────
typedef struct {
    const char* name;
    void (*handler)();
} command_t;

static const command_t commands[] = {
    { "help",    cmd_help    },
    { "clear",   cmd_clear   },
    { "cls",     cmd_clear   },
    { "echo",    cmd_echo    },
    { "version", cmd_version },
    { "ver",     cmd_version },
    { "about",   cmd_about   },
    { "history", cmd_history },
    { "color",   cmd_color   },
    { "mem",     cmd_mem     },
    { "sysinfo", cmd_sysinfo },
    { "tasks",   cmd_tasks   },
    { "ps",      cmd_ps      },
    { "syscall", cmd_syscall },
    { "usermode",cmd_usermode},
    { "exec",    cmd_exec    },
    { "pci",       cmd_pci     },
    { "net",       cmd_net     },
    { "ping",      cmd_ping    },
    { "disk",      cmd_disk    },
    { "diskwrite", cmd_diskwrite },
    { "diskread",  cmd_diskread  },
    { "usb",       cmd_usb     },
    { "beep",      cmd_beep    },
    { "play",      cmd_play    },
    { "gui",       cmd_gui     },
    { "whoami",    cmd_whoami  },
    { "login",     cmd_login   },
    { "logout",    cmd_logout  },
    { "useradd",   cmd_useradd },
    { "users",     cmd_users   },
    { "sha256",    cmd_sha256  },
    { "vyropkg",   cmd_vyropkg },
    { "cpuinfo",   cmd_cpuinfo },
    { "uptime",  cmd_uptime  },
    { "date",    cmd_date    },
    { "time",    cmd_time    },
    { "sleep",   cmd_sleep   },
    { "ls",      cmd_ls      },
    { "pwd",     cmd_pwd     },
    { "cd",      cmd_cd      },
    { "mkdir",   cmd_mkdir   },
    { "touch",   cmd_touch   },
    { "write",   cmd_write   },
    { "cat",     cmd_cat     },
    { "rm",      cmd_rm      },
    { "tree",    cmd_tree    },
    { "reboot",  cmd_reboot  },
};

#define NUM_COMMANDS (sizeof(commands) / sizeof(commands[0]))

static void dispatch(const char* input) {
    if (input[0] == '\0') return;

    parse_args(input);
    if (argc == 0) return;

    for (uint32_t i = 0; i < NUM_COMMANDS; i++) {
        if (kstrcmp(argv[0], commands[i].name) == 0) {
            commands[i].handler();
            return;
        }
    }
    cmd_not_found(argv[0]);
}

// ─────────────────────────────────────────────────
// Print the shell prompt
// ─────────────────────────────────────────────────
static void print_prompt() {
    fs_ensure();
    char path[256];
    vfs_full_path(cwd, path, sizeof(path));
    print_color(current_user(), MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_color("@vyro", MAKE_COLOR(COLOR_LIGHT_GREEN, COLOR_BLACK));
    print_color(":", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_color(path, MAKE_COLOR(COLOR_LIGHT_BLUE, COLOR_BLACK));
    print_color("> ", MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
}

// ─────────────────────────────────────────────────
// shell_init: print welcome message
// ─────────────────────────────────────────────────
void shell_init() {
    print_color("  Type 'help' for commands. Use UP/DOWN for history.\n\n",
                MAKE_COLOR(COLOR_LIGHT_GREY, COLOR_BLACK));
    print_prompt();
}

// ─────────────────────────────────────────────────
// shell_run: main shell loop (never returns)
// ─────────────────────────────────────────────────
void shell_run() {
    static char input[MAX_INPUT];
    static int  input_len = 0;
    static int  hist_nav  = -1;

    while (1) {
        __asm__ volatile("hlt");

        while (keyboard_has_input()) {
            char c = keyboard_getchar();

            // ── Arrow keys ──
            if (c == KEY_UP) {
                if (history_count == 0) continue;
                if (hist_nav == -1)
                    hist_nav = history_count - 1;
                else if (hist_nav > 0)
                    hist_nav--;

                // Clear current line
                for (int i = 0; i < input_len; i++) {
                    print_char('\b');
                }
                kstrcpy(input, history[hist_nav % HISTORY_SIZE]);
                input_len = kstrlen(input);
                print(input);
                continue;
            }

            if (c == KEY_DOWN) {
                if (hist_nav == -1) continue;
                hist_nav++;
                for (int i = 0; i < input_len; i++) {
                    print_char('\b');
                }
                if (hist_nav >= history_count) {
                    hist_nav = -1;
                    input[0] = '\0';
                    input_len = 0;
                } else {
                    kstrcpy(input, history[hist_nav % HISTORY_SIZE]);
                    input_len = kstrlen(input);
                    print(input);
                }
                continue;
            }

            // ── Backspace ──
            if (c == KEY_BACKSPACE) {
                if (input_len > 0) {
                    input_len--;
                    print_char('\b');
                    print_char(' ');
                    print_char('\b');
                }
                continue;
            }

            // ── Enter ──
            if (c == '\n') {
                print_char('\n');
                input[input_len] = '\0';
                history_push(input);
                hist_nav  = -1;
                dispatch(input);
                input_len = 0;
                input[0]  = '\0';
                print_prompt();
                continue;
            }

            // ── Printable character ──
            if (c >= ' ' && c < 127 && input_len < MAX_INPUT - 1) {
                input[input_len++] = c;
                print_char(c);
            }
        }
    }
}
